openapi: 3.0.0
info:
  title: XXXX Auth
  description: "XXXX Service Auth"
  version: '1.0'
  contact:
    name: XXXX Service Auth
    url: 'https://xxx..jp'
    email: xxx@xxxxx.xx
  termsOfService: 'https://xxxx.xx/terms'
servers:
  - url: 'http://localhost:3000'
    description: development
tags:
  # Domains
  - name: auth
    description: Auth
paths:
  # Auth 
  /auth/token:
    $ref: ./paths/auth/token.yaml

